import { BonusCardName } from '../../../common/cards/BonusCardName';
import { BonusCardManifest } from '../CardManifest';
import { Anatomist } from './Anatomist';
import { BackyardBirder } from './BackyardBirder';
import { BirdBander } from './BirdBander';
import { BirdCounter } from './BirdCounter';
import { BirdFeederBonus } from './BirdFeeder';
import { BreedingManager } from './BreedingManager';
import { Cartographer } from './Cartographer';
import { CitizenScientist } from './CitizenScientist';
import { Ecologist } from './Ecologist';
import { EnclosureBuilder } from './EnclosureBuilder';
import { Ethologist } from './Ethologist';
import { Falconer } from './Falconer';
import { FisheryManager } from './FisheryManager';
import { FoodWebExpert } from './FoodWebExpert';
import { Forester } from './Forester';
import { Historian } from './Historian';
import { LargeBirdSpecialist } from './LargeBirdSpecialist';
import { NestBoxBuilder } from './NestBoxBuilder';
import { OmnivoreExpert } from './OmnivoreExpert';
import { PasserineSpecialist } from './PasserineSpecialist';
import { Photographer } from './Photographer';
import { PlatformBuilder } from './PlatformBuilder';
import { PrairieManager } from './PrairieManager';
import { Rodentologist } from './Rodentologist';
import { Viticulturist } from './Viticulturist';
import { WetlandScientist } from './WetlandScientist';

export const BONUS_CARD_MANIFEST: BonusCardManifest = new Map();
BONUS_CARD_MANIFEST.set(BonusCardName.ANATOMIST, () => new Anatomist());
BONUS_CARD_MANIFEST.set(BonusCardName.BACKYARD_BIRDER, () => new BackyardBirder());
BONUS_CARD_MANIFEST.set(BonusCardName.BIRD_BANDER, () => new BirdBander());
BONUS_CARD_MANIFEST.set(BonusCardName.BIRD_COUNTER, () => new BirdCounter());
BONUS_CARD_MANIFEST.set(BonusCardName.BIRD_FEEDER, () => new BirdFeederBonus());
BONUS_CARD_MANIFEST.set(BonusCardName.BREEDING_MANAGER, () => new BreedingManager());
BONUS_CARD_MANIFEST.set(BonusCardName.CARTOGRAPHER, () => new Cartographer());
BONUS_CARD_MANIFEST.set(BonusCardName.CITIZEN_SCIENTIST, () => new CitizenScientist());
BONUS_CARD_MANIFEST.set(BonusCardName.ECOLOGIST, () => new Ecologist());
BONUS_CARD_MANIFEST.set(BonusCardName.ENCLOSURE_BUILDER, () => new EnclosureBuilder());
BONUS_CARD_MANIFEST.set(BonusCardName.ETHOLOGIST, () => new Ethologist());
BONUS_CARD_MANIFEST.set(BonusCardName.FALCONER, () => new Falconer());
BONUS_CARD_MANIFEST.set(BonusCardName.FISHERY_MANAGER, () => new FisheryManager());
BONUS_CARD_MANIFEST.set(BonusCardName.FOOD_WEB_EXPERT, () => new FoodWebExpert());
BONUS_CARD_MANIFEST.set(BonusCardName.FORESTER, () => new Forester());
BONUS_CARD_MANIFEST.set(BonusCardName.HISTORIAN, () => new Historian());
BONUS_CARD_MANIFEST.set(BonusCardName.LARGE_BIRD_SPECIALIST, () => new LargeBirdSpecialist());
BONUS_CARD_MANIFEST.set(BonusCardName.NEST_BOX_BUILDER, () => new NestBoxBuilder());
BONUS_CARD_MANIFEST.set(BonusCardName.OMNIVORE_EXPERT, () => new OmnivoreExpert());
BONUS_CARD_MANIFEST.set(BonusCardName.PASSERINE_SPECIALIST, () => new PasserineSpecialist());
BONUS_CARD_MANIFEST.set(BonusCardName.PHOTOGRAPHER, () => new Photographer());
BONUS_CARD_MANIFEST.set(BonusCardName.PLATFORM_BUILDER, () => new PlatformBuilder());
BONUS_CARD_MANIFEST.set(BonusCardName.PRAIRIE_MANAGER, () => new PrairieManager());
BONUS_CARD_MANIFEST.set(BonusCardName.RODENTOLOGIST, () => new Rodentologist());
BONUS_CARD_MANIFEST.set(BonusCardName.VITICULTURIST, () => new Viticulturist());
BONUS_CARD_MANIFEST.set(BonusCardName.WETLAND_SCIENTIST, () => new WetlandScientist());
