export enum InputType {
  SELECT_ACTION = 'SELECT_ACTION',
  SELECT_BIRD = 'SELECT_BIRD',
  SELECT_FOOD = 'SELECT_FOOD',
  SELECT_HABITAT_SLOT = 'SELECT_HABITAT_SLOT',
  SELECT_EGG_LOCATION = 'SELECT_EGG_LOCATION',
  SELECT_CARDS = 'SELECT_CARDS',
  SELECT_OPTION = 'SELECT_OPTION',
  OR_OPTIONS = 'OR_OPTIONS',
  SELECT_BIRD_TO_KEEP = 'SELECT_BIRD_TO_KEEP',
  SELECT_BONUS_CARD = 'SELECT_BONUS_CARD',
  SELECT_STARTING_FOOD = 'SELECT_STARTING_FOOD',
}
