import { BirdCardName } from '../../../common/cards/BirdCardName';
import { BirdCardManifest } from '../CardManifest';
import { AcornWoodpecker } from './AcornWoodpecker';
import { AmericanAvocet } from './AmericanAvocet';
import { AmericanBittern } from './AmericanBittern';
import { AmericanCoot } from './AmericanCoot';
import { AmericanCrow } from './AmericanCrow';
import { AmericanGoldfinch } from './AmericanGoldfinch';
import { AmericanKestrel } from './AmericanKestrel';
import { AmericanOystercatcher } from './AmericanOystercatcher';
import { AmericanRedstart } from './AmericanRedstart';
import { AmericanRobin } from './AmericanRobin';
import { AmericanWhitePelican } from './AmericanWhitePelican';
import { AmericanWoodcock } from './AmericanWoodcock';
import { Anhinga } from './Anhinga';
import { AnnasHummingbird } from './AnnasHummingbird';
import { AshThroatedFlycatcher } from './AshThroatedFlycatcher';
import { AtlanticPuffin } from './AtlanticPuffin';
import { BairdsSparrow } from './BairdsSparrow';
import { BaldEagle } from './BaldEagle';
import { BaltimoreOriole } from './BaltimoreOriole';
import { BarnOwl } from './BarnOwl';
import { BarnSwallow } from './BarnSwallow';
import { BarredOwl } from './BarredOwl';
import { BarrowsGoldeneye } from './BarrowsGoldeneye';
import { BellsVireo } from './BellsVireo';
import { BeltedKingfisher } from './BeltedKingfisher';
import { BewicksWren } from './BewicksWren';
import { BlackSkimmer } from './BlackSkimmer';
import { BlackTern } from './BlackTern';
import { BlackVulture } from './BlackVulture';
import { BlackBelliedWhistlingDuck } from './BlackBelliedWhistlingDuck';
import { BlackBilledMagpie } from './BlackBilledMagpie';
import { BlackChinnedHummingbird } from './BlackChinnedHummingbird';
import { BlackCrownedNightHeron } from './BlackCrownedNightHeron';
import { BlackNeckedStilt } from './BlackNeckedStilt';
import { BlueGrosbeak } from './BlueGrosbeak';
import { BlueJay } from './BlueJay';
import { BlueGrayGnatcatcher } from './BlueGrayGnatcatcher';
import { BlueWingedWarbler } from './BlueWingedWarbler';
import { Bobolink } from './Bobolink';
import { Brant } from './Brant';
import { BrewersBlackbird } from './BrewersBlackbird';
import { BroadWingedHawk } from './BroadWingedHawk';
import { BronzedCowbird } from './BronzedCowbird';
import { BrownPelican } from './BrownPelican';
import { BrownHeadedCowbird } from './BrownHeadedCowbird';
import { BurrowingOwl } from './BurrowingOwl';
import { Bushtit } from './Bushtit';
import { CaliforniaCondor } from './CaliforniaCondor';
import { CaliforniaQuail } from './CaliforniaQuail';
import { CanadaGoose } from './CanadaGoose';
import { Canvasback } from './Canvasback';
import { CarolinaChickadee } from './CarolinaChickadee';
import { CarolinaWren } from './CarolinaWren';
import { CassinsFinch } from './CassinsFinch';
import { CassinsSparrow } from './CassinsSparrow';
import { CedarWaxwing } from './CedarWaxwing';
import { CeruleanWarbler } from './CeruleanWarbler';
import { ChestnutCollaredLongspur } from './ChestnutCollaredLongspur';
import { ChihuahuanRaven } from './ChihuahuanRaven';
import { ChimneySwift } from './ChimneySwift';
import { ChippingSparrow } from './ChippingSparrow';
import { ClarksGrebe } from './ClarksGrebe';
import { ClarksNutcracker } from './ClarksNutcracker';
import { CommonGrackle } from './CommonGrackle';
import { CommonLoon } from './CommonLoon';
import { CommonMerganser } from './CommonMerganser';
import { CommonNighthawk } from './CommonNighthawk';
import { CommonRaven } from './CommonRaven';
import { CommonYellowthroat } from './CommonYellowthroat';
import { CoopersHawk } from './CoopersHawk';
import { DarkEyedJunco } from './DarkEyedJunco';
import { Dickcissel } from './Dickcissel';
import { DoubleCrestedCormorant } from './DoubleCrestedCormorant';
import { DownyWoodpecker } from './DownyWoodpecker';
import { EasternBluebird } from './EasternBluebird';
import { EasternKingbird } from './EasternKingbird';
import { EasternPhoebe } from './EasternPhoebe';
import { EasternScreechOwl } from './EasternScreechOwl';
import { FerruginousHawk } from './FerruginousHawk';
import { FishCrow } from './FishCrow';
import { ForstersTern } from './ForstersTern';
import { FranklinsGull } from './FranklinsGull';
import { GoldenEagle } from './GoldenEagle';
import { GrasshopperSparrow } from './GrasshopperSparrow';
import { GrayCatbird } from './GrayCatbird';
import { GreatBlueHeron } from './GreatBlueHeron';
import { GreatCrestedFlycatcher } from './GreatCrestedFlycatcher';
import { GreatEgret } from './GreatEgret';
import { GreatHornedOwl } from './GreatHornedOwl';
import { GreaterPrairieChicken } from './GreaterPrairieChicken';
import { GreaterRoadrunner } from './GreaterRoadrunner';
import { GreenHeron } from './GreenHeron';
import { HermitThrush } from './HermitThrush';
import { HoodedMerganser } from './HoodedMerganser';
import { HoodedWarbler } from './HoodedWarbler';
import { HornedLark } from './HornedLark';
import { HouseFinch } from './HouseFinch';
import { HouseWren } from './HouseWren';
import { IncaDove } from './IncaDove';
import { IndigoBunting } from './IndigoBunting';
import { JuniperTitmouse } from './JuniperTitmouse';
import { Killdeer } from './Killdeer';
import { KingRail } from './KingRail';
import { LazuliBunting } from './LazuliBunting';
import { LincolnsSparrow } from './LincolnsSparrow';
import { LoggerheadShrike } from './LoggerheadShrike';
import { Mallard } from './Mallard';
import { MississippiKite } from './MississippiKite';
import { MountainBluebird } from './MountainBluebird';
import { MountainChickadee } from './MountainChickadee';
import { MourningDove } from './MourningDove';
import { NorthernBobwhite } from './NorthernBobwhite';
import { NorthernCardinal } from './NorthernCardinal';
import { NorthernFlicker } from './NorthernFlicker';
import { NorthernHarrier } from './NorthernHarrier';
import { NorthernMockingbird } from './NorthernMockingbird';
import { NorthernShoveler } from './NorthernShoveler';
import { Osprey } from './Osprey';
import { PaintedBunting } from './PaintedBunting';
import { PaintedWhitestart } from './PaintedWhitestart';
import { PeregrineFalcon } from './PeregrineFalcon';
import { PiedBilledGrebe } from './PiedBilledGrebe';
import { PileatedWoodpecker } from './PileatedWoodpecker';
import { PineSiskin } from './PineSiskin';
import { ProthonotaryWarbler } from './ProthonotaryWarbler';
import { PurpleGallinule } from './PurpleGallinule';
import { PurpleMartin } from './PurpleMartin';
import { PygmyNuthatch } from './PygmyNuthatch';
import { RedCrossbill } from './RedCrossbill';
import { RedBelliedWoodpecker } from './RedBelliedWoodpecker';
import { RedBreastedMerganser } from './RedBreastedMerganser';
import { RedBreastedNuthatch } from './RedBreastedNuthatch';
import { RedCockadedWoodpecker } from './RedCockadedWoodpecker';
import { RedEyedVireo } from './RedEyedVireo';
import { RedHeadedWoodpecker } from './RedHeadedWoodpecker';
import { RedShoulderedHawk } from './RedShoulderedHawk';
import { RedTailedHawk } from './RedTailedHawk';
import { RedWingedBlackbird } from './RedWingedBlackbird';
import { RingBilledGull } from './RingBilledGull';
import { RoseBreastedGrosbeak } from './RoseBreastedGrosbeak';
import { RoseateSpoonbill } from './RoseateSpoonbill';
import { RubyCrownedKinglet } from './RubyCrownedKinglet';
import { RubyThroatedHummingbird } from './RubyThroatedHummingbird';
import { RuddyDuck } from './RuddyDuck';
import { SandhillCrane } from './SandhillCrane';
import { SavannahSparrow } from './SavannahSparrow';
import { SaysPhoebe } from './SaysPhoebe';
import { ScaledQuail } from './ScaledQuail';
import { ScissorTailedFlycatcher } from './ScissorTailedFlycatcher';
import { SnowyEgret } from './SnowyEgret';
import { SongSparrow } from './SongSparrow';
import { SpottedOwl } from './SpottedOwl';
import { SpottedSandpiper } from './SpottedSandpiper';
import { SpottedTowhee } from './SpottedTowhee';
import { SpraguesPipit } from './SpraguesPipit';
import { StellersJay } from './StellersJay';
import { SwainsonsHawk } from './SwainsonsHawk';
import { TreeSwallow } from './TreeSwallow';
import { TrumpeterSwan } from './TrumpeterSwan';
import { TuftedTitmouse } from './TuftedTitmouse';
import { TurkeyVulture } from './TurkeyVulture';
import { VauxsSwift } from './VauxsSwift';
import { VioletGreenSwallow } from './VioletGreenSwallow';
import { WesternMeadowlark } from './WesternMeadowlark';
import { WesternTanager } from './WesternTanager';
import { WhiteBreastedNuthatch } from './WhiteBreastedNuthatch';
import { WhiteCrownedSparrow } from './WhiteCrownedSparrow';
import { WhiteFacedIbis } from './WhiteFacedIbis';
import { WhiteThroatedSwift } from './WhiteThroatedSwift';
import { WhoopingCrane } from './WhoopingCrane';
import { WildTurkey } from './WildTurkey';
import { Willet } from './Willet';
import { WilsonsSnipe } from './WilsonsSnipe';
import { WoodDuck } from './WoodDuck';
import { WoodStork } from './WoodStork';
import { YellowBelliedSapsucker } from './YellowBelliedSapsucker';
import { YellowBilledCuckoo } from './YellowBilledCuckoo';
import { YellowBreastedChat } from './YellowBreastedChat';
import { YellowHeadedBlackbird } from './YellowHeadedBlackbird';
import { YellowRumpedWarbler } from './YellowRumpedWarbler';

export const BASE_BIRD_MANIFEST: BirdCardManifest = new Map();
BASE_BIRD_MANIFEST.set(BirdCardName.ACORN_WOODPECKER, () => new AcornWoodpecker());
BASE_BIRD_MANIFEST.set(BirdCardName.AMERICAN_AVOCET, () => new AmericanAvocet());
BASE_BIRD_MANIFEST.set(BirdCardName.AMERICAN_BITTERN, () => new AmericanBittern());
BASE_BIRD_MANIFEST.set(BirdCardName.AMERICAN_COOT, () => new AmericanCoot());
BASE_BIRD_MANIFEST.set(BirdCardName.AMERICAN_CROW, () => new AmericanCrow());
BASE_BIRD_MANIFEST.set(BirdCardName.AMERICAN_GOLDFINCH, () => new AmericanGoldfinch());
BASE_BIRD_MANIFEST.set(BirdCardName.AMERICAN_KESTREL, () => new AmericanKestrel());
BASE_BIRD_MANIFEST.set(BirdCardName.AMERICAN_OYSTERCATCHER, () => new AmericanOystercatcher());
BASE_BIRD_MANIFEST.set(BirdCardName.AMERICAN_REDSTART, () => new AmericanRedstart());
BASE_BIRD_MANIFEST.set(BirdCardName.AMERICAN_ROBIN, () => new AmericanRobin());
BASE_BIRD_MANIFEST.set(BirdCardName.AMERICAN_WHITE_PELICAN, () => new AmericanWhitePelican());
BASE_BIRD_MANIFEST.set(BirdCardName.AMERICAN_WOODCOCK, () => new AmericanWoodcock());
BASE_BIRD_MANIFEST.set(BirdCardName.ANHINGA, () => new Anhinga());
BASE_BIRD_MANIFEST.set(BirdCardName.ANNAS_HUMMINGBIRD, () => new AnnasHummingbird());
BASE_BIRD_MANIFEST.set(BirdCardName.ASH_THROATED_FLYCATCHER, () => new AshThroatedFlycatcher());
BASE_BIRD_MANIFEST.set(BirdCardName.ATLANTIC_PUFFIN, () => new AtlanticPuffin());
BASE_BIRD_MANIFEST.set(BirdCardName.BAIRDS_SPARROW, () => new BairdsSparrow());
BASE_BIRD_MANIFEST.set(BirdCardName.BALD_EAGLE, () => new BaldEagle());
BASE_BIRD_MANIFEST.set(BirdCardName.BALTIMORE_ORIOLE, () => new BaltimoreOriole());
BASE_BIRD_MANIFEST.set(BirdCardName.BARN_OWL, () => new BarnOwl());
BASE_BIRD_MANIFEST.set(BirdCardName.BARN_SWALLOW, () => new BarnSwallow());
BASE_BIRD_MANIFEST.set(BirdCardName.BARRED_OWL, () => new BarredOwl());
BASE_BIRD_MANIFEST.set(BirdCardName.BARROWS_GOLDENEYE, () => new BarrowsGoldeneye());
BASE_BIRD_MANIFEST.set(BirdCardName.BELLS_VIREO, () => new BellsVireo());
BASE_BIRD_MANIFEST.set(BirdCardName.BELTED_KINGFISHER, () => new BeltedKingfisher());
BASE_BIRD_MANIFEST.set(BirdCardName.BEWICKS_WREN, () => new BewicksWren());
BASE_BIRD_MANIFEST.set(BirdCardName.BLACK_SKIMMER, () => new BlackSkimmer());
BASE_BIRD_MANIFEST.set(BirdCardName.BLACK_TERN, () => new BlackTern());
BASE_BIRD_MANIFEST.set(BirdCardName.BLACK_VULTURE, () => new BlackVulture());
BASE_BIRD_MANIFEST.set(BirdCardName.BLACK_BELLIED_WHISTLING_DUCK, () => new BlackBelliedWhistlingDuck());
BASE_BIRD_MANIFEST.set(BirdCardName.BLACK_BILLED_MAGPIE, () => new BlackBilledMagpie());
BASE_BIRD_MANIFEST.set(BirdCardName.BLACK_CHINNED_HUMMINGBIRD, () => new BlackChinnedHummingbird());
BASE_BIRD_MANIFEST.set(BirdCardName.BLACK_CROWNED_NIGHT_HERON, () => new BlackCrownedNightHeron());
BASE_BIRD_MANIFEST.set(BirdCardName.BLACK_NECKED_STILT, () => new BlackNeckedStilt());
BASE_BIRD_MANIFEST.set(BirdCardName.BLUE_GROSBEAK, () => new BlueGrosbeak());
BASE_BIRD_MANIFEST.set(BirdCardName.BLUE_JAY, () => new BlueJay());
BASE_BIRD_MANIFEST.set(BirdCardName.BLUE_GRAY_GNATCATCHER, () => new BlueGrayGnatcatcher());
BASE_BIRD_MANIFEST.set(BirdCardName.BLUE_WINGED_WARBLER, () => new BlueWingedWarbler());
BASE_BIRD_MANIFEST.set(BirdCardName.BOBOLINK, () => new Bobolink());
BASE_BIRD_MANIFEST.set(BirdCardName.BRANT, () => new Brant());
BASE_BIRD_MANIFEST.set(BirdCardName.BREWERS_BLACKBIRD, () => new BrewersBlackbird());
BASE_BIRD_MANIFEST.set(BirdCardName.BROAD_WINGED_HAWK, () => new BroadWingedHawk());
BASE_BIRD_MANIFEST.set(BirdCardName.BRONZED_COWBIRD, () => new BronzedCowbird());
BASE_BIRD_MANIFEST.set(BirdCardName.BROWN_PELICAN, () => new BrownPelican());
BASE_BIRD_MANIFEST.set(BirdCardName.BROWN_HEADED_COWBIRD, () => new BrownHeadedCowbird());
BASE_BIRD_MANIFEST.set(BirdCardName.BURROWING_OWL, () => new BurrowingOwl());
BASE_BIRD_MANIFEST.set(BirdCardName.BUSHTIT, () => new Bushtit());
BASE_BIRD_MANIFEST.set(BirdCardName.CALIFORNIA_CONDOR, () => new CaliforniaCondor());
BASE_BIRD_MANIFEST.set(BirdCardName.CALIFORNIA_QUAIL, () => new CaliforniaQuail());
BASE_BIRD_MANIFEST.set(BirdCardName.CANADA_GOOSE, () => new CanadaGoose());
BASE_BIRD_MANIFEST.set(BirdCardName.CANVASBACK, () => new Canvasback());
BASE_BIRD_MANIFEST.set(BirdCardName.CAROLINA_CHICKADEE, () => new CarolinaChickadee());
BASE_BIRD_MANIFEST.set(BirdCardName.CAROLINA_WREN, () => new CarolinaWren());
BASE_BIRD_MANIFEST.set(BirdCardName.CASSINS_FINCH, () => new CassinsFinch());
BASE_BIRD_MANIFEST.set(BirdCardName.CASSINS_SPARROW, () => new CassinsSparrow());
BASE_BIRD_MANIFEST.set(BirdCardName.CEDAR_WAXWING, () => new CedarWaxwing());
BASE_BIRD_MANIFEST.set(BirdCardName.CERULEAN_WARBLER, () => new CeruleanWarbler());
BASE_BIRD_MANIFEST.set(BirdCardName.CHESTNUT_COLLARED_LONGSPUR, () => new ChestnutCollaredLongspur());
BASE_BIRD_MANIFEST.set(BirdCardName.CHIHUAHUAN_RAVEN, () => new ChihuahuanRaven());
BASE_BIRD_MANIFEST.set(BirdCardName.CHIMNEY_SWIFT, () => new ChimneySwift());
BASE_BIRD_MANIFEST.set(BirdCardName.CHIPPING_SPARROW, () => new ChippingSparrow());
BASE_BIRD_MANIFEST.set(BirdCardName.CLARKS_GREBE, () => new ClarksGrebe());
BASE_BIRD_MANIFEST.set(BirdCardName.CLARKS_NUTCRACKER, () => new ClarksNutcracker());
BASE_BIRD_MANIFEST.set(BirdCardName.COMMON_GRACKLE, () => new CommonGrackle());
BASE_BIRD_MANIFEST.set(BirdCardName.COMMON_LOON, () => new CommonLoon());
BASE_BIRD_MANIFEST.set(BirdCardName.COMMON_MERGANSER, () => new CommonMerganser());
BASE_BIRD_MANIFEST.set(BirdCardName.COMMON_NIGHTHAWK, () => new CommonNighthawk());
BASE_BIRD_MANIFEST.set(BirdCardName.COMMON_RAVEN, () => new CommonRaven());
BASE_BIRD_MANIFEST.set(BirdCardName.COMMON_YELLOWTHROAT, () => new CommonYellowthroat());
BASE_BIRD_MANIFEST.set(BirdCardName.COOPERS_HAWK, () => new CoopersHawk());
BASE_BIRD_MANIFEST.set(BirdCardName.DARK_EYED_JUNCO, () => new DarkEyedJunco());
BASE_BIRD_MANIFEST.set(BirdCardName.DICKCISSEL, () => new Dickcissel());
BASE_BIRD_MANIFEST.set(BirdCardName.DOUBLE_CRESTED_CORMORANT, () => new DoubleCrestedCormorant());
BASE_BIRD_MANIFEST.set(BirdCardName.DOWNY_WOODPECKER, () => new DownyWoodpecker());
BASE_BIRD_MANIFEST.set(BirdCardName.EASTERN_BLUEBIRD, () => new EasternBluebird());
BASE_BIRD_MANIFEST.set(BirdCardName.EASTERN_KINGBIRD, () => new EasternKingbird());
BASE_BIRD_MANIFEST.set(BirdCardName.EASTERN_PHOEBE, () => new EasternPhoebe());
BASE_BIRD_MANIFEST.set(BirdCardName.EASTERN_SCREECH_OWL, () => new EasternScreechOwl());
BASE_BIRD_MANIFEST.set(BirdCardName.FERRUGINOUS_HAWK, () => new FerruginousHawk());
BASE_BIRD_MANIFEST.set(BirdCardName.FISH_CROW, () => new FishCrow());
BASE_BIRD_MANIFEST.set(BirdCardName.FORSTERS_TERN, () => new ForstersTern());
BASE_BIRD_MANIFEST.set(BirdCardName.FRANKLINS_GULL, () => new FranklinsGull());
BASE_BIRD_MANIFEST.set(BirdCardName.GOLDEN_EAGLE, () => new GoldenEagle());
BASE_BIRD_MANIFEST.set(BirdCardName.GRASSHOPPER_SPARROW, () => new GrasshopperSparrow());
BASE_BIRD_MANIFEST.set(BirdCardName.GRAY_CATBIRD, () => new GrayCatbird());
BASE_BIRD_MANIFEST.set(BirdCardName.GREAT_BLUE_HERON, () => new GreatBlueHeron());
BASE_BIRD_MANIFEST.set(BirdCardName.GREAT_CRESTED_FLYCATCHER, () => new GreatCrestedFlycatcher());
BASE_BIRD_MANIFEST.set(BirdCardName.GREAT_EGRET, () => new GreatEgret());
BASE_BIRD_MANIFEST.set(BirdCardName.GREAT_HORNED_OWL, () => new GreatHornedOwl());
BASE_BIRD_MANIFEST.set(BirdCardName.GREATER_PRAIRIE_CHICKEN, () => new GreaterPrairieChicken());
BASE_BIRD_MANIFEST.set(BirdCardName.GREATER_ROADRUNNER, () => new GreaterRoadrunner());
BASE_BIRD_MANIFEST.set(BirdCardName.GREEN_HERON, () => new GreenHeron());
BASE_BIRD_MANIFEST.set(BirdCardName.HERMIT_THRUSH, () => new HermitThrush());
BASE_BIRD_MANIFEST.set(BirdCardName.HOODED_MERGANSER, () => new HoodedMerganser());
BASE_BIRD_MANIFEST.set(BirdCardName.HOODED_WARBLER, () => new HoodedWarbler());
BASE_BIRD_MANIFEST.set(BirdCardName.HORNED_LARK, () => new HornedLark());
BASE_BIRD_MANIFEST.set(BirdCardName.HOUSE_FINCH, () => new HouseFinch());
BASE_BIRD_MANIFEST.set(BirdCardName.HOUSE_WREN, () => new HouseWren());
BASE_BIRD_MANIFEST.set(BirdCardName.INCA_DOVE, () => new IncaDove());
BASE_BIRD_MANIFEST.set(BirdCardName.INDIGO_BUNTING, () => new IndigoBunting());
BASE_BIRD_MANIFEST.set(BirdCardName.JUNIPER_TITMOUSE, () => new JuniperTitmouse());
BASE_BIRD_MANIFEST.set(BirdCardName.KILLDEER, () => new Killdeer());
BASE_BIRD_MANIFEST.set(BirdCardName.KING_RAIL, () => new KingRail());
BASE_BIRD_MANIFEST.set(BirdCardName.LAZULI_BUNTING, () => new LazuliBunting());
BASE_BIRD_MANIFEST.set(BirdCardName.LINCOLNS_SPARROW, () => new LincolnsSparrow());
BASE_BIRD_MANIFEST.set(BirdCardName.LOGGERHEAD_SHRIKE, () => new LoggerheadShrike());
BASE_BIRD_MANIFEST.set(BirdCardName.MALLARD, () => new Mallard());
BASE_BIRD_MANIFEST.set(BirdCardName.MISSISSIPPI_KITE, () => new MississippiKite());
BASE_BIRD_MANIFEST.set(BirdCardName.MOUNTAIN_BLUEBIRD, () => new MountainBluebird());
BASE_BIRD_MANIFEST.set(BirdCardName.MOUNTAIN_CHICKADEE, () => new MountainChickadee());
BASE_BIRD_MANIFEST.set(BirdCardName.MOURNING_DOVE, () => new MourningDove());
BASE_BIRD_MANIFEST.set(BirdCardName.NORTHERN_BOBWHITE, () => new NorthernBobwhite());
BASE_BIRD_MANIFEST.set(BirdCardName.NORTHERN_CARDINAL, () => new NorthernCardinal());
BASE_BIRD_MANIFEST.set(BirdCardName.NORTHERN_FLICKER, () => new NorthernFlicker());
BASE_BIRD_MANIFEST.set(BirdCardName.NORTHERN_HARRIER, () => new NorthernHarrier());
BASE_BIRD_MANIFEST.set(BirdCardName.NORTHERN_MOCKINGBIRD, () => new NorthernMockingbird());
BASE_BIRD_MANIFEST.set(BirdCardName.NORTHERN_SHOVELER, () => new NorthernShoveler());
BASE_BIRD_MANIFEST.set(BirdCardName.OSPREY, () => new Osprey());
BASE_BIRD_MANIFEST.set(BirdCardName.PAINTED_BUNTING, () => new PaintedBunting());
BASE_BIRD_MANIFEST.set(BirdCardName.PAINTED_WHITESTART, () => new PaintedWhitestart());
BASE_BIRD_MANIFEST.set(BirdCardName.PEREGRINE_FALCON, () => new PeregrineFalcon());
BASE_BIRD_MANIFEST.set(BirdCardName.PIED_BILLED_GREBE, () => new PiedBilledGrebe());
BASE_BIRD_MANIFEST.set(BirdCardName.PILEATED_WOODPECKER, () => new PileatedWoodpecker());
BASE_BIRD_MANIFEST.set(BirdCardName.PINE_SISKIN, () => new PineSiskin());
BASE_BIRD_MANIFEST.set(BirdCardName.PROTHONOTARY_WARBLER, () => new ProthonotaryWarbler());
BASE_BIRD_MANIFEST.set(BirdCardName.PURPLE_GALLINULE, () => new PurpleGallinule());
BASE_BIRD_MANIFEST.set(BirdCardName.PURPLE_MARTIN, () => new PurpleMartin());
BASE_BIRD_MANIFEST.set(BirdCardName.PYGMY_NUTHATCH, () => new PygmyNuthatch());
BASE_BIRD_MANIFEST.set(BirdCardName.RED_CROSSBILL, () => new RedCrossbill());
BASE_BIRD_MANIFEST.set(BirdCardName.RED_BELLIED_WOODPECKER, () => new RedBelliedWoodpecker());
BASE_BIRD_MANIFEST.set(BirdCardName.RED_BREASTED_MERGANSER, () => new RedBreastedMerganser());
BASE_BIRD_MANIFEST.set(BirdCardName.RED_BREASTED_NUTHATCH, () => new RedBreastedNuthatch());
BASE_BIRD_MANIFEST.set(BirdCardName.RED_COCKADED_WOODPECKER, () => new RedCockadedWoodpecker());
BASE_BIRD_MANIFEST.set(BirdCardName.RED_EYED_VIREO, () => new RedEyedVireo());
BASE_BIRD_MANIFEST.set(BirdCardName.RED_HEADED_WOODPECKER, () => new RedHeadedWoodpecker());
BASE_BIRD_MANIFEST.set(BirdCardName.RED_SHOULDERED_HAWK, () => new RedShoulderedHawk());
BASE_BIRD_MANIFEST.set(BirdCardName.RED_TAILED_HAWK, () => new RedTailedHawk());
BASE_BIRD_MANIFEST.set(BirdCardName.RED_WINGED_BLACKBIRD, () => new RedWingedBlackbird());
BASE_BIRD_MANIFEST.set(BirdCardName.RING_BILLED_GULL, () => new RingBilledGull());
BASE_BIRD_MANIFEST.set(BirdCardName.ROSE_BREASTED_GROSBEAK, () => new RoseBreastedGrosbeak());
BASE_BIRD_MANIFEST.set(BirdCardName.ROSEATE_SPOONBILL, () => new RoseateSpoonbill());
BASE_BIRD_MANIFEST.set(BirdCardName.RUBY_CROWNED_KINGLET, () => new RubyCrownedKinglet());
BASE_BIRD_MANIFEST.set(BirdCardName.RUBY_THROATED_HUMMINGBIRD, () => new RubyThroatedHummingbird());
BASE_BIRD_MANIFEST.set(BirdCardName.RUDDY_DUCK, () => new RuddyDuck());
BASE_BIRD_MANIFEST.set(BirdCardName.SANDHILL_CRANE, () => new SandhillCrane());
BASE_BIRD_MANIFEST.set(BirdCardName.SAVANNAH_SPARROW, () => new SavannahSparrow());
BASE_BIRD_MANIFEST.set(BirdCardName.SAYS_PHOEBE, () => new SaysPhoebe());
BASE_BIRD_MANIFEST.set(BirdCardName.SCALED_QUAIL, () => new ScaledQuail());
BASE_BIRD_MANIFEST.set(BirdCardName.SCISSOR_TAILED_FLYCATCHER, () => new ScissorTailedFlycatcher());
BASE_BIRD_MANIFEST.set(BirdCardName.SNOWY_EGRET, () => new SnowyEgret());
BASE_BIRD_MANIFEST.set(BirdCardName.SONG_SPARROW, () => new SongSparrow());
BASE_BIRD_MANIFEST.set(BirdCardName.SPOTTED_OWL, () => new SpottedOwl());
BASE_BIRD_MANIFEST.set(BirdCardName.SPOTTED_SANDPIPER, () => new SpottedSandpiper());
BASE_BIRD_MANIFEST.set(BirdCardName.SPOTTED_TOWHEE, () => new SpottedTowhee());
BASE_BIRD_MANIFEST.set(BirdCardName.SPRAGUES_PIPIT, () => new SpraguesPipit());
BASE_BIRD_MANIFEST.set(BirdCardName.STELLERS_JAY, () => new StellersJay());
BASE_BIRD_MANIFEST.set(BirdCardName.SWAINSONS_HAWK, () => new SwainsonsHawk());
BASE_BIRD_MANIFEST.set(BirdCardName.TREE_SWALLOW, () => new TreeSwallow());
BASE_BIRD_MANIFEST.set(BirdCardName.TRUMPETER_SWAN, () => new TrumpeterSwan());
BASE_BIRD_MANIFEST.set(BirdCardName.TUFTED_TITMOUSE, () => new TuftedTitmouse());
BASE_BIRD_MANIFEST.set(BirdCardName.TURKEY_VULTURE, () => new TurkeyVulture());
BASE_BIRD_MANIFEST.set(BirdCardName.VAUXS_SWIFT, () => new VauxsSwift());
BASE_BIRD_MANIFEST.set(BirdCardName.VIOLET_GREEN_SWALLOW, () => new VioletGreenSwallow());
BASE_BIRD_MANIFEST.set(BirdCardName.WESTERN_MEADOWLARK, () => new WesternMeadowlark());
BASE_BIRD_MANIFEST.set(BirdCardName.WESTERN_TANAGER, () => new WesternTanager());
BASE_BIRD_MANIFEST.set(BirdCardName.WHITE_BREASTED_NUTHATCH, () => new WhiteBreastedNuthatch());
BASE_BIRD_MANIFEST.set(BirdCardName.WHITE_CROWNED_SPARROW, () => new WhiteCrownedSparrow());
BASE_BIRD_MANIFEST.set(BirdCardName.WHITE_FACED_IBIS, () => new WhiteFacedIbis());
BASE_BIRD_MANIFEST.set(BirdCardName.WHITE_THROATED_SWIFT, () => new WhiteThroatedSwift());
BASE_BIRD_MANIFEST.set(BirdCardName.WHOOPING_CRANE, () => new WhoopingCrane());
BASE_BIRD_MANIFEST.set(BirdCardName.WILD_TURKEY, () => new WildTurkey());
BASE_BIRD_MANIFEST.set(BirdCardName.WILLET, () => new Willet());
BASE_BIRD_MANIFEST.set(BirdCardName.WILSONS_SNIPE, () => new WilsonsSnipe());
BASE_BIRD_MANIFEST.set(BirdCardName.WOOD_DUCK, () => new WoodDuck());
BASE_BIRD_MANIFEST.set(BirdCardName.WOOD_STORK, () => new WoodStork());
BASE_BIRD_MANIFEST.set(BirdCardName.YELLOW_BELLIED_SAPSUCKER, () => new YellowBelliedSapsucker());
BASE_BIRD_MANIFEST.set(BirdCardName.YELLOW_BILLED_CUCKOO, () => new YellowBilledCuckoo());
BASE_BIRD_MANIFEST.set(BirdCardName.YELLOW_BREASTED_CHAT, () => new YellowBreastedChat());
BASE_BIRD_MANIFEST.set(BirdCardName.YELLOW_HEADED_BLACKBIRD, () => new YellowHeadedBlackbird());
BASE_BIRD_MANIFEST.set(BirdCardName.YELLOW_RUMPED_WARBLER, () => new YellowRumpedWarbler());
