import { BirdCardName } from '../../../common/cards/BirdCardName';
import { BirdCardManifest } from '../CardManifest';
import { AmericanRobin } from './AmericanRobin';
import { BarnSwallow } from './BarnSwallow';
import { BlueJay } from './BlueJay';
import { CanadaGoose } from './CanadaGoose';
import { CedarWaxwing } from './CedarWaxwing';
import { ChimneySwift } from './ChimneySwift';
import { CommonRaven } from './CommonRaven';
import { DarkEyedJunco } from './DarkEyedJunco';
import { EasternBluebird } from './EasternBluebird';
import { EasternPhoebe } from './EasternPhoebe';
import { EuropeanStarling } from './EuropeanStarling';
import { GreatBlueHeron } from './GreatBlueHeron';
import { HouseFinch } from './HouseFinch';
import { Killdeer } from './Killdeer';
import { Mallard } from './Mallard';
import { MourningDove } from './MourningDove';
import { NorthernCardinal } from './NorthernCardinal';
import { Osprey } from './Osprey';
import { RedTailedHawk } from './RedTailedHawk';
import { RubyThroatedHummingbird } from './RubyThroatedHummingbird';

export const BASE_BIRD_MANIFEST: BirdCardManifest = new Map();
BASE_BIRD_MANIFEST.set(BirdCardName.AMERICAN_ROBIN, () => new AmericanRobin());
BASE_BIRD_MANIFEST.set(BirdCardName.BARN_SWALLOW, () => new BarnSwallow());
BASE_BIRD_MANIFEST.set(BirdCardName.BLUE_JAY, () => new BlueJay());
BASE_BIRD_MANIFEST.set(BirdCardName.CANADA_GOOSE, () => new CanadaGoose());
BASE_BIRD_MANIFEST.set(BirdCardName.CEDAR_WAXWING, () => new CedarWaxwing());
BASE_BIRD_MANIFEST.set(BirdCardName.CHIMNEY_SWIFT, () => new ChimneySwift());
BASE_BIRD_MANIFEST.set(BirdCardName.COMMON_RAVEN, () => new CommonRaven());
BASE_BIRD_MANIFEST.set(BirdCardName.DARK_EYED_JUNCO, () => new DarkEyedJunco());
BASE_BIRD_MANIFEST.set(BirdCardName.EASTERN_BLUEBIRD, () => new EasternBluebird());
BASE_BIRD_MANIFEST.set(BirdCardName.EASTERN_PHOEBE, () => new EasternPhoebe());
BASE_BIRD_MANIFEST.set(BirdCardName.EUROPEAN_STARLING, () => new EuropeanStarling());
BASE_BIRD_MANIFEST.set(BirdCardName.GREAT_BLUE_HERON, () => new GreatBlueHeron());
BASE_BIRD_MANIFEST.set(BirdCardName.HOUSE_FINCH, () => new HouseFinch());
BASE_BIRD_MANIFEST.set(BirdCardName.KILLDEER, () => new Killdeer());
BASE_BIRD_MANIFEST.set(BirdCardName.MALLARD, () => new Mallard());
BASE_BIRD_MANIFEST.set(BirdCardName.MOURNING_DOVE, () => new MourningDove());
BASE_BIRD_MANIFEST.set(BirdCardName.NORTHERN_CARDINAL, () => new NorthernCardinal());
BASE_BIRD_MANIFEST.set(BirdCardName.OSPREY, () => new Osprey());
BASE_BIRD_MANIFEST.set(BirdCardName.RED_TAILED_HAWK, () => new RedTailedHawk());
BASE_BIRD_MANIFEST.set(BirdCardName.RUBY_THROATED_HUMMINGBIRD, () => new RubyThroatedHummingbird());
